#!/bin/sh
LOC=$(dirname "$0")
FB=$LOC/fastbasic-fp
CA65=$LOC/ca65
LD65=$LOC/ld65
INCS=$LOC/asminc

usage() {
    "$FB" -h
    exit 1
}

error() {
    echo "$(basename "$0"): error, $*"
    echo "Try '$(basename "$0") -h' for help."
    exit 1
}

# Process options
CFGFILE=$LOC/fastbasic.cfg
OPTS=""
ASMOPTS="-tatari -g"
for i do
    shift
    case "$i" in
        -h)
            usage
            ;;
        -X:*)
            ASMOPTS="$ASMOPTS ${i#-X:}"
            ;;
        -S:*)
            set -- "$@" "--start-addr" "${i#-S:}"
            ;;
        -C:*)
            CFGFILE="${i#-C:}"
            ;;
        -[a-zA-Z0-9_]*)
            OPTS="$OPTS $i"
            ;;
        -*)
            error "invalid option '$i'"
            ;;
        *.asm|*.s)
            obj=${i%.*}.o
            echo "Assembling '$i' to '$obj'."
            "$CA65" -I "$INCS" $ASMOPTS -o "$obj" -l "${i%.*}.lst" "$i" || exit 1
            set -- "$@" "$obj"
            ;;
        *.o)
            set -- "$@" "$i"
            ;;
        *)
            [ -n "$PROG" ] && error "specify only one basic file"
            PROG="$i"
            ;;
    esac
done

ASM=${PROG%.*}.asm
OBJ=${PROG%.*}.o
XEX=${PROG%.*}.xex
LBL=${PROG%.*}.lbl
set -- "$@" "$OBJ"

[ -z "$PROG" ]         && error "no input file"
[ ! -f "$PROG" ]       && error "input file '$PROG' does not exists"
[ "$PROG" -ef "$ASM" ] && error "input file '$PROG' same as ASM file"
[ "$PROG" -ef "$XEX" ] && error "input file '$PROG' same as XEX file"

echo "Compiling '$PROG' to assembler '$ASM'."
"$FB" $OPTS "$PROG" "$ASM" || exit 1
echo "Assembling '$ASM' to '$OBJ'."
"$CA65" -I "$INCS" $ASMOPTS "$ASM" -o "$OBJ" || exit 1
echo "Linking $@ to Atari executable file '$XEX'."
"$LD65" -C "$CFGFILE" "$@" -o "$XEX" -Ln "$LBL" "$FB.lib" || exit 1

